### PR TITLE
4 token that create to scam people and we need to take it down

### PR DESCRIPTION
**Pull request by ballgamer56**
DPCKbTuuu2fejYt6sD6FpMsSJuE2Z7K17iwMFF6KZuEL
7RsEZB7wH1aTQN7p9VBt7hwW4A9BLtg9cqQNoLgTLgjr
CJJTaJ5Nn6CFRm7jtarwdXSaNApVWFRRU3nLwFSAjPAs
3SnjWdQCC6aR9fFQ879pbgoWTzbv1vbFjUYeUQJXpz7W

### CODE REVIEW

**Comment by twiggysmile** [comment]
Hello!

The provided tokens created on the Wavesplatform but we do not administrate these tokens. Moreover, these assets are smart-assets which can additional trading conditions. So, please be most attentive while trading with smart-assets. 

Before sending, receiving and trading crypto assets, educate yourself to make informed decisions. Crypto assets are volatile, and the prices can go up and down. Carefully evaluate your trading goals and the financial risk you are willing to take. Please beware that Wavesplatform does not provide financial, tax, or legal advice. You should make such decisions on your own or consult with reliable experts.

On the other hand, smart-assets created not so long ago, and at the moment we work on building an algorithm for reading the conditions of contracts embedded in smart-assets.

PS: You have excluded 3370 assets in this pull request. Do not need to do so.

**Comment by ballgamer56** [comment]
But we can't sell our token even thought we meant the requirement of their code. Goldmine limit its selling price to 1.00000001 waves and up but the issuer able to sell it lower than that and he keep refilling his order make it impossible to sell.
Godsend is from same issuer as Goldmine and have the same exact code (Iidk how exact they are but it behave a lot like each other) and exact same price but the issuer didn't sell any on this toke.
GWWG use the same code (or similar)
And YOVI is a little different to other 3. All of them (apart from Godsend for now) are unsellable. You can only buy but never sell because how their script work. I already discuss about these token (mostly Goldmine) on waves community forum [https://forum.wavesplatform.com/t/scam-token-scam-not-spam/10460/10]. Most people can't sell these coin as well. Please reconsider or explain why you think they're not a scam token

**Comment by twiggysmile** [comment]
Everyone can always **send back**, **burn** or **hide** spam tokens. It’s quite dangerous to buy something unknown.

**Comment by ballgamer56** [comment]
Yea.. you're right. I don't know about other who buy these coin but I got it for free(Goldmine) so I want to sell it so I buy more but I can't. I'm sure some people fall for it but some are just buy it normally. Guess I'll send all of these token back. Also I can't seem to burn YOVI. Is that possible to code burn restriction into a smart asset?

**Comment by twiggysmile** [comment]
Yes, it is possible to add several restrictions in smart-assets, such as burning and withdrawing.

**Pull request closed without merging**
